import Link from 'next/link';

export const metadata = {
  title: 'Terms of Use - Arithmo AI',
  description: 'Terms of Use for Arithmo AI platform.',
};

export default function TermsPage() {
  return (
    <div className="legal-page">
      <div className="bg-glow" />
      <div className="legal-container">
        <Link href="/" className="legal-back">&lt;- Back to Arithmo AI</Link>
        <h1>Terms of Use</h1>
        <p className="legal-date">Last updated: April 1, 2026</p>

        <h2>1. Acceptance of Terms</h2>
        <p>By accessing and using Arithmo AI (&quot;the Service&quot;), you agree to be bound by these Terms of Use. If you do not agree, please do not use the Service.</p>

        <h2>2. Description of Service</h2>
        <p>Arithmo AI is an artificial intelligence chatbot platform that provides conversational AI assistance powered by large language models. The Service offers general knowledge, code assistance, mathematical help, and educational support.</p>

        <h2>3. AI Disclaimer</h2>
        <p><strong>Important:</strong> Arithmo AI is powered by artificial intelligence and may produce incorrect, incomplete, or outdated information. AI-generated responses should not be treated as professional advice (legal, medical, financial, or otherwise). Users should independently verify all critical information.</p>

        <h2>4. User Accounts</h2>
        <p>To use the Service, you must create an account with a valid email address. You are responsible for maintaining the confidentiality of your password and for all activities under your account.</p>

        <h2>5. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the Service for unlawful purposes</li>
          <li>Attempt to exploit, abuse, or overload the Service</li>
          <li>Generate malicious, harmful, or deceptive content</li>
          <li>Reverse-engineer any part of the Service</li>
          <li>Violate any applicable laws or regulations</li>
        </ul>

        <h2>6. Intellectual Property</h2>
        <p>The Arithmo AI brand, logo, and platform design are the property of the Service operator. Content generated by the AI is provided as-is and users may use it at their own discretion and risk.</p>

        <h2>7. Data and Privacy</h2>
        <p>Your use of the Service is also governed by our <Link href="/privacy">Privacy Policy</Link>. We store your chat history to provide persistent conversations. We do not sell or share your personal data with third parties.</p>

        <h2>8. Limitation of Liability</h2>
        <p>The Service is provided &quot;as is&quot; without warranties of any kind. We shall not be liable for any damages arising from the use or inability to use the Service, including any reliance on AI-generated content.</p>

        <h2>9. Modifications</h2>
        <p>We reserve the right to modify these Terms at any time. Changes will be effective upon posting. Your continued use constitutes acceptance of the modified Terms.</p>

        <h2>10. Contact</h2>
        <p>For questions about these Terms, contact us at: <a href="mailto:astitvapandey1203@gmail.com">astitvapandey1203@gmail.com</a></p>
      </div>
    </div>
  );
}
