import Link from 'next/link';

export const metadata = {
  title: 'Terms of Use - Arithmo AI',
  description: 'Terms of Use for Arithmo AI platform.',
};

export default function TermsPage() {
  return (
    <div className="legal-page">
      <div className="bg-glow" />
      <div className="legal-container">
        <Link href="/" className="legal-back">&lt;- Back to Arithmo AI</Link>
        <h1>Terms of Use</h1>
        <p className="legal-date">Last updated: May 5, 2026</p>

        <h2>1. Acceptance of Terms</h2>
        <p>By accessing or using Arithmo AI, a product of Tech You, you agree to these Terms. If you do not agree, please do not use the service.</p>

        <h2>2. Description of Service</h2>
        <p>Arithmo AI provides AI-powered chat, tutoring, research assistance, image-related features, and productivity tools. AI responses may be generated by third-party model providers and should be reviewed carefully before relying on them.</p>

        <h2>3. AI Disclaimer</h2>
        <p>Arithmo AI may produce incorrect, incomplete, or outdated information. It is not a substitute for professional legal, medical, financial, academic, or safety advice. You are responsible for verifying important information.</p>

        <h2>4. User Accounts</h2>
        <p>You must use accurate account information and keep your account secure. Authentication is handled through Firebase Authentication, while MongoDB stores app data such as plan status, usage, settings, and chats.</p>

        <h2>5. Acceptable Use</h2>
        <p>You agree not to misuse Arithmo AI, including by attempting to overload the service, bypass usage limits, generate harmful content, reverse-engineer the platform, or violate applicable laws.</p>

        <h2>6. Payments</h2>
        <p>Paid plans may unlock higher limits or premium features. All payments made for Arithmo AI services are final. No refunds will be provided once a payment has been successfully completed.</p>

        <h2>7. Termination</h2>
        <p>We reserve the right to suspend or permanently terminate any user account without prior notice if the user engages in abusive, harmful, or inappropriate behavior, if unusual or suspicious activity is detected, or if the account is being misused or violating platform policies.</p>

        <h2>8. Eligibility</h2>
        <p>Arithmo AI is not intended for users under the age of 13. If we determine that an account is being used by a person below 13 years of age, we reserve the right to terminate the account immediately.</p>

        <h2>9. Intellectual Property</h2>
        <p>The Arithmo AI name, logo, interface, and platform design belong to Tech You or its operators. AI-generated content is provided as-is, and users are responsible for how they use it.</p>

        <h2>10. Data and Privacy</h2>
        <p>Your use of Arithmo AI is also governed by our <Link href="/privacy">Privacy Policy</Link>, which explains how account data, chat data, and usage information are handled.</p>

        <h2>11. Limitation of Liability</h2>
        <p>The service is provided as-is without warranties of any kind. We are not responsible for losses or damages resulting from use of the service or reliance on AI-generated content.</p>

        <h2>12. Contact</h2>
        <p>For questions about these Terms, contact us at: <a href="mailto:techyou2026@gmail.com">techyou2026@gmail.com</a></p>
      </div>
    </div>
  );
}
